security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    providers:
        my_provider:
            entity:
                class: AppBundle:User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        public:
            pattern: ^/login
            security: false
        main:
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
            provider: my_provider
    access_control:
        - { path: ^/, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
